lovishprabhakar/CSCentral-Hacktoberfest

- Code/dictionary.html
made the required changes resolving issue #3
> made style changes to dictionary.html

- Code/README.md
- Code/currency-change.html
- Code/dictionary.html
- Code/index.html
- Code/js/currency.js
- Code/js/news.js
- Code/news.html
Added cards for Currency Exchange as well as News and connected them to the respective API. #1 #2
> Added Currency Change and News cards

- Code/index.html
> Making the images clickable

- Code/css/index.css
- Code/index.html
I changed the position of the search bar and also added some new styles to the search bar and the hamburger icon
> Added some new styles

- Code/css/index.css
> added hover effects

- Code/caesar.html
- Code/index.html
- Code/js/caesar.js
- Code/js/home.js
This PR adds a new card as described in this issue #28
> Add Caesar Cipher Card

- Code/caesar.html
- Code/contest.html
- Code/css/global.css
- Code/currency-change.html
- Code/dictionary.html
- Code/encrypt-decrypt.html
- Code/index.html
- Code/js/common.js
- Code/location.html
- Code/news.html
- Code/notefy.html
- Code/pdf-scan.html
- Code/postal-code.html
- Code/qr-gen.html
- Code/translation.html
> Created Footer

- Code/caesar.html
- Code/contest.html
- Code/css/global.css
- Code/currency-change.html
- Code/dictionary.html
- Code/encrypt-decrypt.html
- Code/location.html
- Code/news.html
- Code/notefy.html
- Code/pdf-scan.html
- Code/postal-code.html
- Code/qr-gen.html
- Code/translation.html
> Added Hero Space

- Code/index.html
This Actually fixes 2 issues #62  and #64
> I have Modified the code for Index page where Footer was a blank box (fixes #62 & #64)

- Code/index.html
Closed the div correctly so that the footer spans the entire width.
> changed footer width to 100%

- .vscode/launch.json
- Code/css/bootstrap/bootstrap.min.css
- Code/css/index.css
- Code/index.html
I have Modified the Bar
this fixes #67 
before:
After:
> Changes in Nav Bar

- Code/compile-run.html
- Code/css/index.css
- Code/ideiframe/c.html
- Code/ideiframe/cpp.html
- Code/ideiframe/java.html
- Code/ideiframe/php.html
- Code/ideiframe/python.html
- Code/index.html
- Code/js/compile.js
- Code/js/home.js
- Code/news.html
- README.md
- Added code-compile-run feature using JDoodle API
- Allowed languages are C, C++, Python, Java, and PHP
- Made required changes on index.html, index.css, and js/home.hs
- Thoroughly check the code and maintained the code standard
- Did unit testing of my feature and all test were passed
- No breaking changes
> Added code-compile-run feature 

- Code/index.html
I've added some simple animation on cards.
when you refresh the website, the cards are appearing and coming from top to bottom.
> added animation

- Code/encrypt-decrypt.html
- Code/js/encrypt-decrypt.js
Added some features using crypto-js:
```
- To Base64
- From Base64
- To MD5
```
> Added few features to encrypt-decrypt page

- Code/css/index.css
- Code/index.html
Hey @lovishprabhakar I have added link to this repo in the footer section so that anyone on the page can come directly to you repo by clicking on the link. I have also removed the list style and text decoration from ul-> li. See the screenshot below for better look:-
- Before
- After 
Hope you like it. Please merge my pull request and add the hacktoberfest-accepted label on it. Thank you!
> Modified footer

- Code/caesar.html
- Code/compile-run.html
- Code/contest.html
- Code/currency-change.html
- Code/currentweather.html
- Code/dictionary.html
- Code/encrypt-decrypt.html
- Code/live_calendar.html
- Code/location.html
- Code/news.html
- Code/notefy.html
- Code/pdf-scan.html
- Code/postal-code.html
- Code/qr-gen.html
- Code/random-joke-generator.html
- Code/randomcolor-palette.html
> added favicon to all pages

- Code/css/index.css
- Code/index.html
- Code/js/home.js
I have implemented the scroll back to top button with a customization that fits with the theme of the website.
> Added Scroll Back-to-top button

- Code/css/index.css
i have successfully created the navbar responsive in all windows
> successfully added

- README.md
The preview image in Readme.md was an old one. Added a new, updated image in place of it.
> Updating the preview image in Readme.md

- Code/index.html
Kindly check the share buttons as added @lovishprabhakar 
Closes #97
> Share buttons Added

- Code/index.html
@lovishprabhakar kindly merge and label this with hacktoberfest.
> target changed

- Code/.vscode/settings.json
- Code/index.html
Added a paragraph about contact me section. 
grouped the social icons together.
>  Made changes to footer

- Code/index.html
A simple calculator. HTML, CSS, JS files added. Please review and merge.
> Adding calculator

- Code/index.html
A simple web app that converter.
> Adding Name to Avatar Converter

- Code/postal-code.html
- Clicking enter will now submit the form and return data. Earlier, only clicking the button returned data
- Embbeded the <input> tags in <form> and created a handleSubmit() function, which calls 'displayPostalResult()' and  'event.preventDefault()' to prevent reload.
- No UI changes. Only functionality improved
> Form Implemented

- Code/index.html
Removed Unnecessary logos from the footer 
now its look like this
> removed unnecessary logos

- Code/js/qr-gen.js
- Code/qr-gen.html
with this change in code, user can get the QRcode according to size of their choice.
> 	 resolved the issueno.129 and made changes in qr-gen.html and qr-gen.js

- .eslintrc.json
- .gitignore
- .husky/pre-commit
- .prettierignore
- .prettierrc.json
- package-lock.json
- package.json
- playwright.config.ts
- tests/example.spec.ts
- to make sure the application(s) work as expected
These libraries for static code analysis will make code formatting easier in the project
- ESLint - introduces linting coding rules for Playwright test files (TypeScript only)
- Prettier - will help with formatting all files
The Husky library will provide high code standard
- Husky - will run lint scripts with each commit
> [Issue#136] playwright, and libs for static code analysis - init config

- Code/css/index.css
- Code/index.html
This pull request addresses two issues, #141  and #142, where we resolved the dropdown issue in the navbar and updated the Twitter logo in the footer.
1. **Dropdown Issue**: Fixed the bug related to the appearance of a scrollbar in the dropdown menu in the project's navigation bar. The dropdown menu now displays its content without the unwanted scrollbar.
2. **Twitter Logo**: Updated the Twitter logo in the footer from the old logo to the new Twitter logo, aligning it with the latest branding standards.
Please review this pull request and consider merging it into the main project repository. If there are any further adjustments needed or if you have any feedback, please let us know. Thank you for your consideration.
Closes #141 , #142
> Fix the twitter logo on the footer and Fix scrollbar from dropdown in navbar.

- index.html
This pull request addresses the bug issue #140, where we resolved the issue of the misplaced GitHub icon in the footer. The fix involved moving the `index.html` file to the root directory and then hosting the project using GitHub Pages. As a result, the GitHub icon is now properly placed and organized within the footer.
1. **Directory Structure**: Moved the `index.html` file to the root directory of the project.
Please review this pull request and consider merging it into the main project repository. If any further adjustments are needed or if you have any feedback, please let us know. Thank you for your consideration.
Closes #140
> Move to index.html to the root dir for removing the misplaced github icons.

- Code/js/qr-gen.js
- Code/qr-gen.html
Changed the QR code generating library from `qrcode.js` to `qrious`.
[Qrious](https://github.com/neocotic/qrious#install)
Fixes #147
> Added option to change colour of the QR

- src/pages/base.page.ts
- src/pages/pin-postal-index-number.page.ts
- tests/cer-currency-exchange.spec.ts
- tests/pin-postal-index-number.spec.ts
- tests for the PIN Postal Index Number page
- fix formatting in base.page.ts
- update comment to more appropriate in cer-currency-exchange.spec.ts
> [Issue#145] add playwright tests - pin page

- src/pages/swf-subsequent-weather-forecast.page.ts
- tests/swf-subsequent-weather-forecast.spec.ts
- add tests for the SWF - Subsequent Weather Forecast page
- update swf page
> Issue#145 add playwright tests - swf page

- playwright.config.ts
- src/components/footer.component.ts
- src/pages/base.page.ts
- src/pages/ccr-code-compile-run.page.ts
- src/pages/cer-currency-exchange.page.ts
- src/pages/home.page.ts
- src/pages/swf-subsequent-weather-forecast.page.ts
- tests/ccr-code-compile-run.spec.ts
- tests/cer-currency-exchange.spec.ts
- tests/homepage.spec.ts
- tests/pin-postal-index-number.spec.ts
- tests/swf-subsequent-weather-forecast.spec.ts
- add tests for the CCR - Code Compile Run page
- update ccr page
- fix style: add empty lines for better readability
- fix incorrect page reference
- refactor tests:
-> replace `wait(8_000)` with `waitForPageToLoadURL()`
-> replace `addUnit()` with `performCurrencyConversionWithXtoXunit()`
-> add `performCurrencyConversionWith1to1Unit()`
-> simplify page.url assertion
-> fix `navigateToPage()`
-> add `searchForWeatherInLocation()`
> [Issue#145] add playwright tests - ccr page

- README.md
Update README.md doc, so that it includes the following info:
- testing tech stack: Playwright && TypeScript
- installation prerequisites
- repository setup (required so that tools for static code analysis could be used)
- test solution setup and running
> [ISSUE#156] update readme

- Code/currency-change.html
- Code/js/currency.js
- add row to currency-change.html with id="more-success-error-msg"
- inject success message html into the rowset mentioned above, the message says: "Converted successfully"
- replace browser's alert with error message that says the same: "Invalid input"
Please see the below screen shots:
> [ISSUE#152] [FIX/FEAT] more conversions - add success and error messages

- README.md
Sample PR to test for CI workflow.
> Removing Hacktoberfest part from ReadMe
